server:
  port: 9300
spring:
  application:
    name: cloud-service-9300
  redis:
    host: 43.142.28.177
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10  #最大连接数
        max-idle: 10    #最大空闲连接数
        min-idle: 1     #最小空闲连接数
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null  #JSON处理时忽略非空字段

logging:
  level:
    cn.com.kai: debug