spring:
      cloud:
        gateway:
          discovery:
            locator:  #是否和注册中心结合使用，true表示可以直接使用应用服务名称进行服务调用
              enabled: true
        #=============================================请求路由规则=======================================
          routes:
            # 路由ID，要求唯一，没有固定规则，自定义，建议写服务名
          - id: service8001
            # uri：目标服务地址，即请求转发后的地址；
            # lb表示负载均衡
            uri: lb://cloud-service-8001
            # 断言：路由条件，匹配HTTP请求内容
            predicates:
            - Path=/order/**  # 需要匹配的地址
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]  #当前请求在该时间之后才能被执行，可以通过[ZonedDateTime.now()]获取待区域的时间
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]  #当前请求在该时间之前才能被执行
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]  #当前请求必须在该时间段内才能被执行
#            - Cookie=mycookie,mycookievalue  #根据cookie及其参数进行判断
#            - Header=X-Request-Id, \d+   #根据请求头进行判断
#            ...
            # 过滤器
            filters:
            - StripPrefix=1   #截取路径位数
            - CheckAuth=123456

          - id: service9001
            uri: lb://cloud-service-9001
            predicates:
            - Path=/repertory/**
            filters:
            - StripPrefix=1

        #=============================================Gateway解决跨域的配置信息=======================================
#          globalcors:
#            cors-configurations:
#              '[/**]':  //允许跨域访问的资源
#                allowedOrigins: "*"  //跨域允许的来源,*表示允许所有
#                allowedMethods:
#                - GET
#                - POST




